replicaCount: 3
image:
  repository: 123456789012.dkr.ecr.us-east-1.amazonaws.com/sreorg/go-ingestion
  tag: latest
  pullPolicy: IfNotPresent
service:
  type: ClusterIP
  port: 80
resources:
  limits:
    cpu: 500m
    memory: 512Mi
  requests:
    cpu: 200m
    memory: 256Mi
env:
  - name: AWS_REGION
    value: us-east-1
  - name: KINESIS_STREAM
    value: sreorg-events
